name: Create release binaries for octowise

on:
  release:
    types: [published]

jobs:
  release-matrix:
    name: release octowise binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.14, windows-2016, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn make
      - run: npx rimraf "out/**/!(*.exe|*.deb|*.AppImage|*.dmg|*.zip)"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "out/**/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
