name: Release October for Windows/Linux

on:
  release:
    types: [published]

jobs:
  release:
    name: Release October
    runs-on: [macOS] # We can cross compile but need to be on macOS to notarise
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - run: wails version
